services:
  lazybeagle:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never
    container_name: lazybeagle
    networks: [proxy]
    volumes:
      - ${CONTAINERS}/lazybeagle/config:/www/assets:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.beagle.rule=Host(`lazybeagle.themysterymachine.net`) || Host(`dash.themysterymachine.net`) || Host(`dashboard.themysterymachine.net`)
      - traefik.http.routers.beagle.entrypoints=websecure
      - traefik.http.routers.beagle.tls=true
      - traefik.http.services.beagle.loadbalancer.server.port=6524
    restart: unless-stopped

networks:
  proxy:
    external: true
