# LazyBeagle Dashboard Configuration
# This file controls all aspects of your home network dashboard

# Dashboard Settings
dashboard:
  # Background settings
  background:
    theme: 'nature' # Theme: nature, urban, minimal, space, ocean, mountains
    rotation_enabled: true # Enable automatic background rotation
    rotation_interval: 60 # Minutes between background changes
    quality: 80 # Image quality (1-100)
    blur_overlay: 0.3 # Background blur overlay (0-1)

  # Time and locale settings
  time:
    format: '24' # Time format: "12" or "24"
    timezone: 'auto' # Timezone: "auto" or specific timezone like "America/New_York"

  # Weather settings
  weather:
    location: 'Surrey, CA' # Default weather location
    units: 'metric' # Units: "metric" (Celsius), "imperial" (Fahrenheit), "kelvin"
    refresh_interval: 10 # Minutes between weather updates

  # Grid layout settings
  grid:
    columns: 12 # Number of grid columns
    rows: 12 # Number of grid rows
    gap: 16 # Gap between grid items (pixels)
    padding: 24 # Padding around grid container (pixels)

  # Card layout (sizes/positions for the dashboard grid)
  layout:
    cards:
      clock:
        col: 4
        row: 1
        width: 4
        height: 3
      search:
        col: 2
        row: 4
        width: 6
        height: 1
      weather:
        width: 2
        height: 3
      upcoming_tv:
        width: 3
        height: 2
      upcoming_movies:
        width: 3
        height: 2
      links:
        col: 1
        row: 12
        width: 12
        height: 2

# Theme Configuration
themes:
  nature:
    name: 'Nature'
    keywords: ['nature', 'forest', 'mountains', 'landscape', 'trees', 'wilderness']
    collections: ['1114848', '1065976']

  urban:
    name: 'Urban'
    keywords: ['city', 'urban', 'architecture', 'buildings', 'skyline', 'street']
    collections: ['1114849', '1065396']

  minimal:
    name: 'Minimal'
    keywords: ['minimal', 'clean', 'simple', 'abstract', 'geometric', 'modern']
    collections: ['1114847', '1065392']

  space:
    name: 'Space'
    keywords: ['space', 'galaxy', 'stars', 'nebula', 'cosmos', 'astronomy']
    collections: ['1114850', '1065397']

  ocean:
    name: 'Ocean'
    keywords: ['ocean', 'sea', 'water', 'waves', 'beach', 'coastal']
    collections: ['1114851', '1065398']

  mountains:
    name: 'Mountains'
    keywords: ['mountains', 'peaks', 'alpine', 'snow', 'hiking', 'summit']
    collections: ['1114852', '1065399']

# Application Metadata
app:
  name: 'LazyBeagle'
  version: '1.0.0'
  author: 'Rogerio Caceres'
  description: 'Home Network Dashboard'

# Security Settings
security:
  # Enable/disable external API calls
  allow_external_apis: true

  # Enable/disable local network service calls
  allow_local_network: true

  # CORS settings for API calls
  cors_enabled: true
