# Web Links
links:
  - type: 'LINK'
    name: 'YouTube'
    url: 'https://youtube.com'
    description: 'YouTube'
    icon: 'asset:svg:youtube'
    enabled: true

  - type: 'LINK'
    name: 'TV Shows'
    url: 'https://sonarr.themysterymachine.net'
    description: 'TV Shows'
    icon: 'lucide:tv'
    enabled: true

  - type: 'LINK'
    name: 'Movies'
    url: 'https://radarr.themysterymachine.net'
    description: 'Movies'
    icon: 'lucide:film'
    enabled: true

  - type: 'LINK'
    name: 'Books'
    url: 'https://lazylibrarian.themysterymachine.net'
    description: 'Books'
    icon: 'lucide:book-open'
    enabled: true

  - type: 'APP'
    name: 'Queue'
    description: 'Download Queue'
    icon: 'lucide:download'
    enabled: true
    provider: 'nzbget'
    props:
      pollInterval: 10000
    panel:
      gridWidth: 6
      gridHeight: 8

  - type: 'GROUP'
    name: 'Downloads'
    description: 'Downloads'
    icon: 'lucide:shopping-cart'
    enabled: true
    links:
      - type: 'LINK'
        name: 'NZBGet'
        url: 'https://nzbget.themysterymachine.net'
        description: 'Download Qeueue Manager'
        icon: 'asset:svg:nzbget'
        enabled: true

      - type: 'LINK'
        name: 'Prowlarr'
        url: 'https://prowlarr.themysterymachine.net'
        description: 'Download Indexers'
        icon: 'asset:svg:prowlarr'
        enabled: true
      - type: 'GROUP'
        name: 'Search'
        description: 'Search Engines'
        icon: 'lucide:search'
        enabled: true
        links:
          - type: 'LINK'
            name: 'NZB Geek'
            url: 'https://nzbgeek.info/dashboard.php'
            description: 'NZB Search'
            icon: 'asset:png:nzbgeek'
            enabled: true
          - type: 'LINK'
            name: 'NZB Planet'
            url: 'https://nzbplanet.net'
            description: 'NZB Search'
            enabled: true

  - type: 'GROUP'
    name: 'Shopping'
    description: 'Shopping'
    icon: 'lucide:shopping-cart'
    enabled: true
    links:
      - type: 'LINK'
        name: 'Amazon'
        url: 'https://amazon.ca'
        description: 'Shopping'
        icon: 'asset:svg:amazon'
        enabled: true

      - type: 'LINK'
        name: 'Costco'
        url: 'https://costco.ca'
        description: 'Costco'
        enabled: true

      - type: 'LINK'
        name: 'Realtor'
        url: 'https://realtor.ca'
        description: 'Shopping'
        enabled: true

      - type: 'LINK'
        name: 'Wayfair'
        url: 'https://wayfair.ca'
        description: 'Wayfair'
        enabled: true

      - type: 'LINK'
        name: 'London Drugs'
        url: 'https://londondrugs.com'
        description: 'London Drugs'
        enabled: true

      - type: 'LINK'
        name: 'Save On Foods'
        url: 'https://saveonfoods.com'
        description: 'Save On Foods'
        enabled: true

  - type: 'GROUP'
    name: 'Banking'
    description: 'Banking'
    icon: 'lucide:banknote'
    enabled: true
    links:
      - type: 'LINK'
        name: 'RBC'
        url: 'https://royalbank.com'
        description: 'RBC'
        enabled: true

      - type: 'LINK'
        name: 'BMO'
        url: 'https://bmo.com'
        description: 'BMO'
        enabled: true

      - type: 'LINK'
        name: 'Scotiabank'
        url: 'https://scotiabank.com'
        description: 'Scotiabank'
        enabled: true

  - type: 'GROUP'
    name: 'Gaming'
    description: 'Gaming'
    icon: 'lucide:gamepad-2'
    enabled: true
    links:
      - type: 'LINK'
        name: 'Playnow'
        url: 'https://playnow.com'
        description: 'Lottery'
        enabled: true
      - type: 'LINK'
        name: 'Steam Store'
        url: 'https://store.steampowered.com/'
        description: 'Steam Store'
        enabled: true
      - type: 'LINK'
        name: 'Fanatical'
        url: 'https://fanatical.com'
        description: 'Books'
        enabled: true
      - type: 'LINK'
        name: 'Elden Ring'
        url: 'https://eldenring.wiki.fextralife.com/Elden+Ring+Wiki'
        description: 'Elden Ring Wiki'
        enabled: true

  - type: 'GROUP'
    name: 'Books'
    description: 'Books'
    icon: 'lucide:book-open'
    enabled: true
    links:
      - type: 'LINK'
        name: 'lazylibrarian'
        url: 'https://lazylibrarian.themysterymachine.net'
        description: 'Books'
        icon: 'lucide:book-open'
        enabled: true

      - type: 'LINK'
        name: 'komga'
        url: 'https://komga.themysterymachine.net'
        description: 'Comics'
        icon: 'asset:svg:komga'
        enabled: true

      - type: 'LINK'
        name: 'calibre-web'
        url: 'https://calibreweb.themysterymachine.net'
        description: 'Ebooks'
        icon: 'asset:svg:calibreweb'
        enabled: true
      - type: 'LINK'
        name: 'Calibre'
        url: 'https://calibre.themysterymachine.net'
        description: 'Ebooks'
        icon: 'asset:svg:calibre'
        enabled: true
      - type: 'LINK'
        name: 'Mylar3'
        url: 'https://mylar.themysterymachine.net'
        description: 'Ebooks'
        icon: 'asset:png:mylar3'
        enabled: true

  # Network Services
  - type: 'GROUP'
    name: 'Dev'
    description: 'Development'
    icon: 'lucide:code'
    enabled: true
    links:
      - type: 'LINK'
        name: 'n8n'
        url: 'https://n8n.themysterymachine.net'
        description: 'n8n'
        icon: 'asset:svg:n8n'
        enabled: true
      - type: 'LINK'
        name: 'Open AI'
        url: 'https://platform.openai.com/docs/overview'
        description: 'Open AI API Platform'
        icon: 'asset:svg:openai'
        enabled: true
      - type: 'LINK'
        name: 'Apple Developer'
        url: 'https://developer.apple.com'
        description: 'Apple Developer'
        enabled: true
      - type: 'LINK'
        name: 'Dashboard Icons'
        url: 'https://dashboardicons.com/'
        description: 'Dashboard Icons'
        enabled: true

  # Network Services
  - type: 'GROUP'
    name: '3D Printing'
    description: '3D Printing'
    icon: 'lucide:printer'
    enabled: true
    links:
      - type: 'LINK'
        name: 'Bambu Labs'
        url: 'https://bambulab.com'
        description: 'Bambu Labs'
        enabled: true
      - type: 'LINK'
        name: 'Thangs'
        url: 'https://thangs.com'
        description: 'Thangs'
        enabled: true
      - type: 'LINK'
        name: 'MakerWorld'
        url: 'https://makerworld.com/en'
        description: 'MakerWorld'
        enabled: true

  # Network Services
  - type: 'GROUP'
    name: 'Network'
    description: 'Network Services'
    icon: 'lucide:network'
    enabled: true
    links:
      - type: 'LINK'
        name: 'Home Assistant'
        url: 'https://homeassistant.themysterymachine.net'
        description: 'Home Assistant'
        icon: 'asset:svg:home-assistant'
        enabled: true

      - type: 'LINK'
        name: 'Pi-hole'
        url: 'https://pihole.themysterymachine.net'
        description: 'DNS Filter'
        icon: 'asset:svg:pi-hole'
        enabled: true

      - type: 'LINK'
        name: 'Forgejo'
        url: 'https://forgejo.themysterymachine.net'
        description: 'Git Server'
        icon: 'asset:svg:forgejo'
        enabled: true

      - type: 'LINK'
        name: 'Router'
        url: 'https://gateway.themysterymachine.net'
        description: 'Network Admin'
        icon: 'asset:svg:ubiquiti-unifi'
        enabled: true

      - type: 'LINK'
        name: 'NAS'
        url: 'https://bob.themysterymachine.net'
        description: 'NAS'
        icon: 'asset:svg:ugreen-nas'
        enabled: true

      - type: 'LINK'
        name: 'Portainer'
        url: 'https://portainer.themysterymachine.net'
        description: 'Docker Management'
        icon: 'asset:svg:portainer'
        enabled: true

      - type: 'LINK'
        name: 'Zabbix'
        url: 'https://zabbix.themysterymachine.net'
        description: 'Monitoring'
        icon: 'asset:svg:zabbix'
        enabled: true
